### ISSUE TITLE
Show nicknames above player heads

### ISSUE THREAD

**Issue by danthedaniel** [MajekDev/HexNicks#109]
**Describe the solution you'd like**
There should be a config option to apply nicknames to the name tag above players' heads.

**Comment by Majekdor** [comment]
This is not possible without some very hacky code that HexNicks isn't going to try to implement. If another plugin wants to do it then they're free to use the HexNicks placeholder to get the nickname.

**Comment by danthedaniel** [comment]
I'd be happy to implement this hacky code for just my server. I've been playing with the scoreboard API but it's not straightforward (first few attempts have had no effect).

Can you give me some pseudo-code to accomplish this? Thanks so much for any help!

**Comment by Majekdor** [comment]
I don't know enough about it to provide pseudocode. I haven't tried to do it in over 2 years.

But this [thread](https://github.com/EssentialsX/Essentials/issues/2517) explains why Essentials wouldn't add this feature either and some more reasons/workarounds.

**Comment by danthedaniel** [comment]
Thanks!
