### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by Majekdor** [MajekDev/HexNicks#29]
### Add a wiki here on GitHub for HexNicks.
https://github.com/Majekdor/HexNicks/wiki

## Documentation Needed 📘 
- [x] Commands
- [x] Permissions
- [x] Color Formatting
- [x] Built-In Chat Formatter
- [x] Developer API Usage
- [ ] How to use with Essentials
- [x] Legacy color explanation
- [x] Placeholder Information
- [ ] Example Nicknames
- [x] Config Options

If anyone has anything else they believe should be documented comment on this issue.

**Comment by sargeow** [comment]
-all commands that are actively used for the plugin
-all perms listed for the plugin and what commands/properties they handle
-all placeholders listed and what they do
-some sort of documentation talking about chatformatting maybe even linking them the chatformatting plugin
-brief description of what mini message is and basics on how to use it?
-documentation on how the gradient command works and alot of examples for /nickcolor <gradient...>
-possibly a video to show case its uses
-link to old color formatting aka &6, &b, &d etc and explanation on how that works
-bascially provide more example for use case
-def have sarge in there somewhere

**Comment by Majekdor** [comment]
I finally get to close this! :D Docs are available [here](https://hexnicks.majek.dev).
