### ISSUE TITLE
More Transformations

### ISSUE THREAD

**Issue by Masta2222** [MajekDev/HexNicks#36]
**Is your feature request related to a problem? Please describe.**

 - Honestly, there really is no problem. I think though that by adding more transformations to your plugin, the player will be able to have more accessibility or restrictions. In my case, I would like to disable the function of allowing people to bold their names. 

**Describe the solution you'd like**

 - Add a permission where the player would have to have to be able to bold or use certain transformations. 

**Describe alternatives you've considered**

 - None unfortunately, this is the only plugin I know that can really use Hex Codes the way I want. 

**Additional context**
 - Add any other context or screenshots about the feature request here.

We discussed this in the discord! I appreciate all the help! :)
![image](https://user-images.githubusercontent.com/93496568/141707686-26a9a4f5-571b-4522-95d4-46317eace45c.png)

**Comment by Majekdor** [comment]
There's now a config option for this. View it [here](https://github.com/MajekDev/HexNicks/blob/bd9ba6362b584c4df581cbe2b4cf514209128979/src/main/resources/config.yml#L43).
