### ISSUE TITLE
MySQL autoReconnect=true database URL conflict

### ISSUE THREAD

**Issue by WillysHub** [MajekDev/HexNicks#39]
**Describe the bug**
When trying to add '?autoReconnect=true&' as an option after the database name, it conflicts with the already existing '?useSSL=false'.

The error shown is
`Malformed database URL, failed to parse the connection string near '?useSSL=false'.`

Currently there is no way to remove the '?' and there is still an error if the '&' is removed after '?autoReconnect=true'

**To Reproduce**
1. Add '?autoReconnect=true&' after your database name in the config file.
2. Turn on the server
3. Read errors that show while HexNicks loads.

**Expected behavior**
HexNicks successfully connects to the Database with the additional setting.

**Software (please complete the following information):**
 - Purpur
 - Minecraft 1.17.1
 - OpenJDK 16
 - HexNicks 2.1.4

**Additional context**
Discussed in Discord, just added this here as requested.

**Comment by Majekdor** [comment]
Fixed in this [commit](https://github.com/MajekDev/HexNicks/commit/bd9ba6362b584c4df581cbe2b4cf514209128979). There's now an option in the config with the other MySQL options.
