### ISSUE TITLE
Duplicated nicks

### ISSUE THREAD

**Issue by ehetteNandaYo** [MajekDev/HexNicks#43]
**Is your feature request related to a problem? Please describe.**

Players can use other players name, EssentialsX nicks avoids this which is nice

**Describe the solution you'd like**
Deny players using the same nicks and names of players that already joined the server

**Comment by Majekdor** [comment]
I like this idea as a config option! I'll add it in the next update.

**Comment by Majekdor** [comment]
This is added as a config option in the latest version!

**Comment by ehetteNandaYo** [comment]
Great but 2 things

1. If the player has for example "Terminator" as nick and tries to change to "&bTerminator" it sasys someone already has a nick, this should be bypassed for the player that owns the nick

2. I can still use nicks of players that arent nicks, so for example "Jon" is a minecraft name I can use Jon as nick, so maybe you could ad as an option to the plugin, to check for player names checking playerdata files? or maybe essentials ? or also you could populate the database with players when they jon the game and if someone tries to use that deny it.

**Comment by Majekdor** [comment]
Haha you'd be correct on both accounts. Will reopen the issue and fix both.
