### ISSUE TITLE
Decorative legacy codes working when disabled

### ISSUE THREAD

**Issue by Log1x** [MajekDev/HexNicks#80]
**Describe the bug**
Players are able to use bold/underline in their names when using https://rgb.birdflop.com/ – but doing `&lTest` does not work.

I have `hexnicks.decoration.*` negated (set to `false` in luckperms) as well as:

```yaml
disabled-decorations:
- italic
- bold
- strikethrough
- obfuscated
- underlined
```

set in my config. This appears to only be affecting legacy colors (as seen with the birdflop generator) when mixed with hex.

**To Reproduce**
1. Disable all decorations
2. Negate the `hexnicks.decoration.*` permission
3. Generate a name with bold/underline with birdflop
4. Set nickname, it will work.

**Expected behavior**
For bold/underline/other decorations to be filtered.

**Screenshots**
![Screenshot](https://i.imgur.com/UDHPsbd.png)

**Software (please complete the following information):**
 - Server Implementation: Paper
 - Minecraft Version: 1.19
 - Java Version: 17
 - Plugin Version: Latest

**Comment by Majekdor** [comment]
Bug reported stated it's fixed as of `v3.0.2`.
