### ISSUE TITLE
Colors only

### ISSUE THREAD

**Issue by Bleachsicle** [MajekDev/HexNicks#85]
Would love to see a feature where players can only have access to change their colors but their nick has to match their username
usage:

real name: bwaa

/nickcolor <#249d9f>b<#478ebf>w<#697edf>a<#8c6fff>a
Successfully changes the color of their username to the desired hexs

/nickcolor <#249d9f>J<#478ebf>a<#697edf>t<#8c6fff>t
Doesn't change nick because they try changing their actual name

Basically, a way for players to change the color of each individual character of their name, but can't change their nick (want them to keep their actual MC name)

/nickcolor only allows for someone to apply a single color to their name right now I'm pretty sure. Unless I am using it wrong

**Comment by Majekdor** [comment]
Resolved in v3.0.5. Thank you for the issue! This was a good change.
