### ISSUE TITLE
Plugin not unload in the server restart 

### ISSUE THREAD

**Issue by thiagogebrimm** [MajekDev/HexNicks#92]
**Describe the bug**
The plugin crashes when deactivated and does not shut down the server

**To Reproduce**
1. Restart a server

**Expected behavior**
The plugin shuts down without crashing and the server restarts

**Screenshots**
![image](https://user-images.githubusercontent.com/75040244/209708923-1ecad7de-1307-4082-ab2d-61613dfd32c1.png)

**Software (please complete the following information):**
 - Server Implementation: Purpur
 - Minecraft Version 1.19.3
 - Java Version 17
 - Plugin Version 3.0.5

**Additional context**

**Comment by thiagogebrimm** [comment]
[15:55:17 WARN]: [nChat] The PlaceholderAPI placeholder translator took more than 50ms to process the input "%hexnicks_nick%" for Y2k_vinix (took 135.84ms).

**Comment by Majekdor** [comment]
I assume you're using MySQL? I've seen this issue with others using it and have a fix I believe. People should be testing it now.

**Comment by Majekdor** [comment]
Was this fixed in v3.1.0?

**Comment by Majekdor** [comment]
Closing this as completed given a lack of response and the fact that it should be fixed in v3.1.0.

If this issue still persists please reopen this issue.
