### ISSUE TITLE
Hexnicks shutdown takes too long.

### ISSUE THREAD

**Issue by madebygood** [MajekDev/HexNicks#93]
**Describe the bug**
The server has about 300 concurrent users.

When I try to reboot it takes a very long time.

is it possible to solve it?

**Expected behavior**

**Screenshots**
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/43653581/211919417-1084d578-81c6-4178-afb1-37d5f3d5969e.png">

**Software (please complete the following information):**
- 1.19.2 purpur
- JDK 19
- HexNicks Version : 3.0.5

**Comment by Majekdor** [comment]
Was this fixed in v3.1.0?

**Comment by Majekdor** [comment]
Closing this as completed given a lack of response and the fact that it should be fixed in v3.1.0.

If this issue still persists please reopen this issue.
