### ISSUE TITLE
Codes seperate permissions.

### ISSUE THREAD

**Issue by TheWeirdCoder** [MajekDev/HexNicks#96]
So i wanted to make it where players rankup like this "Supporter Nick with colors, Supporter+ Nick with colors and codes, Patron Nick with colors, codes, and hex" But there isn't a seperate permission for &l &o etc

So i think there should be a permission like hexnicks.code.bold or hexnicks.code.italic etc

**Comment by Majekdor** [comment]
That functionality exists. See [here](https://github.com/MajekDev/HexNicks/blob/main/src/main/resources/plugin.yml#L104)
